[package]
name = "exploit"
version = "0.1.0"
edition = "2021"

[dependencies]
smol_str = {version = "0.1.24", default-features = false}

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
